feat: Replace twitter logo with the x thing
videojs/font pull request #50
Opened 2024-03-06 23:38 UTC by mister-ben

- Updates the Twitter logo to the new X one 😮‍💨
- Update node and node-sass

2024-03-18 23:34 UTC, thijstriemstra approved these changes

2024-03-18 23:40 UTC, thijstriemstra requested changes
The table in the readme also needs to be updated: https://github.com/videojs/font?tab=readme-ov-file#version-4-default-unicode-values

2024-03-25 14:41 UTC, mister-ben commented
> The table in the readme also needs to be updated: https://github.com/videojs/font?tab=readme-ov-file#version-4-default-unicode-values

The icon name remains the same, so no change needed there.

2024-06-06 17:08 UTC, misteroneill approved these changes

2024-06-06 17:08 UTC, merged